# Generated by Django 5.1.7 on 2025-03-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(default=2, upload_to='pages/images/'),
            preserve_default=False,
        ),
    ]
